import fs from "node:fs";
import path from "node:path";

const artifactPath = path.join("artifacts", "contracts", "Ribbon.sol", "Ribbon.json");
const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8")) as { abi: unknown };
const json = `${JSON.stringify(artifact.abi, null, 2)}\n`;
const ts = `// Generated by scripts/export-abi.ts. Do not edit.\nexport const ribbonAbi = ${JSON.stringify(artifact.abi, null, 2)} as const\n`;

for (const file of [
  path.join("web", "src", "abi", "Ribbon.json"),
  path.join("server", "src", "abi", "Ribbon.json"),
]) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, json);
}

for (const file of [
  path.join("web", "src", "abi", "Ribbon.ts"),
  path.join("server", "src", "abi", "Ribbon.ts"),
]) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, ts);
}

console.log("Exported Ribbon ABI to web/ and server/.");
